pg-cache:
  enabled: true
  table-name: cache_data
  default-ttl-seconds: 30
  cleanup-enabled: true
  cleanup-limit: 10
  cleanup-cron: "*/10 * * * * *"
  caches:
    cache1:
      ttl-seconds: 5

  admin-datasource:
    url: jdbc:postgresql://localhost:5432/pgcache
    username: pgcache-admin
    #password:

  user-read-datasource:
    url: jdbc:postgresql://localhost:5432/pgcache
    username: pgcache-user
    #password:
    maximum-pool-size: 5

  user-write-datasource:
    url: jdbc:postgresql://localhost:5432/pgcache
    username: pgcache-user
    #password:
    maximum-pool-size: 2