pg-cache:
  enabled: true
  use-universal-serializer: true
  table-name: cache_data
  default-ttl-seconds: 30
  cleanup-enabled: true
  cleanup-limit: 10
  cleanup-cron: "*/10 * * * * *"
  caches:
    cache1:
      ttl-seconds: 5
    cache2:
      disabled: true

  async:
    enabled: true
    writeThreads: 3
    clearThreads: 2

  admin-datasource:
    url: jdbc:postgresql://localhost:5432/pgcache
    username: pgcache-admin
    connectionTimeoutMs: 2000
    #password:
    maximum-pool-size: 1

  user-read-datasource:
    url: jdbc:postgresql://localhost:5432/pgcache
    username: pgcache-user
    connectionTimeoutMs: 2000
    #password:
    maximum-pool-size: 5

  user-write-datasource:
    url: jdbc:postgresql://localhost:5432/pgcache
    username: pgcache-user
    connectionTimeoutMs: 2000
    #password:
    maximum-pool-size: 2

resilience4j:
  circuitbreaker:
    configs:
      pg-cache:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        permittedNumberOfCallsInHalfOpenState: 3

    instances:
      pg-cache-cache1:
        baseConfig: pg-cache
        slidingWindowSize: 1
        minimumNumberOfCalls: 1
        failureRateThreshold: 100
        waitDurationInOpenState: 60s
      pg-cache-cache2:
        baseConfig: pg-cache