spring:
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          enabled: true
          max-active: 32
          max-idle: 16
          min-idle: 8
          max-wait: 1000ms

pg-cache:
  enabled: true
  custom-serializers: false
  table-name: cache_data_perf
  default-ttl-seconds: 60
  cleanup-enabled: false
  caches:
    cache1:
      ttl-seconds: 5
    cache2:
      disabled: true # switch to false to test

  datasource:
    url: jdbc:postgresql://localhost:5432/pgcache
    username: pgcache-user
    connectionTimeoutMs: 2000
    #password:
    maximum-pool-size: 50
  admin-datasource:
    url: jdbc:postgresql://localhost:5432/pgcache
    username: pgcache-admin
    connectionTimeoutMs: 2000
    #password:
    maximum-pool-size: 1
  write-datasource:
    url: jdbc:postgresql://localhost:5432/pgcache
    username: pgcache-user
    connectionTimeoutMs: 2000
    #password:
    maximum-pool-size: 10

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 30s
        minimumNumberOfCalls: 10